### ISSUE TITLE
`try_remove ()` may return true when nothing is removed

### ISSUE THREAD

**Issue by BrainBlasted** [AaronErhardt/Relm4#103]
` WidgetPlus::try_remove()` may return true when nothing is removed. It only checks that `self` is one of a set number of supported widgets, and then calls the appropriate `remove()` function. However, there are no guarantees that the child is actually removed. Each of these APIs are a no-op when you pass a widget that's not one of their children, and it's still possible to do that with `try_remove()`.

**Comment by AaronErhardt** [comment]
Thanks for pointing this out! 

I wonder, is there a way to fix this? Maybe with something like `widget.parent() == self` you could find out whether the remove will actually work. Otherwise I will update the docs to describe the behavior correctly.

**Comment by BrainBlasted** [comment]
`widget.parent()` isn't reliable, because there can be widgets between the "container" and the "child". For example, `GtkHeaderBar` contains multiple `GtkBox`es that it puts the start, end, and center children in. `widget.parent()` on one of the children would return a box instead of the `GtkHeaderBar`.

**Comment by AaronErhardt** [comment]
I've updated the docs. And this will be likely replaced by something more robust in the next major release.
