### ISSUE TITLE
Using libadwaita

### ISSUE THREAD

**Issue by overlisted** [AaronErhardt/relm4#11]
I can't use `libadwaita::ApplicationWindow` with `view!`:
```
error[E0277]: the trait bound `libadwaita::ApplicationWindow: DefaultWidget` is not satisfied
  --> src/main.rs:35:1
   |
35 | #[widget]
   | ^^^^^^^^^ the trait `DefaultWidget` is not implemented for `libadwaita::ApplicationWindow`
   |
   = note: required by `relm4::util::default_widgets::DefaultWidget::default_widget`
   = note: this error originates in the attribute macro `widget` (in Nightly builds, run with -Z macro-backtrace for more info)
```

Also, `RelmApp` doesn't seem to like that the root of my app is `libadwaita::ApplicationWindow`:
```
error[E0271]: type mismatch resolving `<AppWidgets as Widgets<AppModel, ()>>::Root == gtk4::ApplicationWindow`
  --> src/main.rs:79:15
   |
79 |     let app = RelmApp::new(model);
   |               ^^^^^^^^^^^^^^^^^^^ expected struct `gtk4::ApplicationWindow`, found struct `libadwaita::ApplicationWindow`
   |
  ::: /home/overlisted/.cargo/git/checkouts/relm4-2fc0f2271e83be1c/172c278/src/app.rs:18:45
   |
18 |     Model::Widgets: WidgetsTrait<Model, (), Root = gtk::ApplicationWindow> + 'static,
   |                                             ----------------------------- required by this bound in `RelmApp`
```

Do you have any plans on adding support for libadwaita? It's a pretty important library

**Comment by AaronErhardt** [comment]
I'm glad you asked :)
I planned to add support for libadwaita but mostly focused on polishing the macros and the book until now.

As a workaround you can for now use a function that returns a `libadwaita::ApplicationWindow` or other libadwaita widgets like described here: https://aaronerhardt.github.io/relm4-book/book/widget_macro_reference.html#functions

Yet, that will not fix the issue that a `gtk::ApplicationWindow` is required by RelmApp. I would like to have only one RelmApp struct for both GTK and libadwaita widgets if possible and I hope I can use the fact that `libadwaita::ApplicationWindow` is actually derived from `gtk::ApplicationWindow` and implements `IsA<gtk::ApplicationWindow>`.

I will try to install libadwaita on my system and to add support for libadwaita-rs behind a feature flag.

**Comment by AaronErhardt** [comment]
@overlisted I just pushed the initial support for libadwaita to the libadwaita branch. If you want, you can try it out. I had some problems though on my system, e.g. I couldn't use `adw::prelude::ApplicationWindowExt` and using `gtk::prelude::GtkWindowExt` for the set_child method instead caused a runtime error. But maybe you're more successful.

Anyway, in case you're satisfied with the initial support and don't find anything missing, I'll merge the new features into main.

**Comment by overlisted** [comment]
I just tried your branch and I think I found the problem. If you just import `adw::prelude::*`, the expansion of `view!` will just call `gtk::prelude::ApplicationWindowExt::set_child`, but once you import `adw::traits::ApplicationWindowExt`, you get this error:
```
error[E0034]: multiple applicable items in scope
  --> src/main.rs:43:13
   |
43 |             set_child = Some(&gtk::Box) {
   |             ^^^^^^^^^ multiple `set_child` found
   |
   = note: candidate #1 is defined in an impl of the trait `gtk4::prelude::ButtonExt` for the type `O`
   = note: candidate #2 is defined in an impl of the trait `gtk4::prelude::ComboBoxExt` for the type `O`
   = note: candidate #3 is defined in an impl of the trait `gtk4::prelude::FlowBoxChildExt` for the type `O`
   = note: candidate #4 is defined in an impl of the trait `gtk4::prelude::FrameExt` for the type `O`
   = note: and 6 others
help: disambiguate the associated function for candidate #1
   |
36 | gtk4::prelude::ButtonExt::set_child(&#[widget], Some)
   |
help: disambiguate the associated function for candidate #2
   |
36 | gtk4::prelude::ComboBoxExt::set_child(&#[widget], Some)
   |
help: disambiguate the associated function for candidate #3
   |
36 | gtk4::prelude::FlowBoxChildExt::set_child(&#[widget], Some)
   |
help: disambiguate the associated function for candidate #4
   |
36 | gtk4::prelude::FrameExt::set_child(&#[widget], Some)
   |
```

I can think of 2 ways to solve this:
1) An additional syntax that can be used specify which setter will be used in `view!`? Like `ApplicationWindowExt::set_child = Some(&gtk::Box) {`.
2) Find out why that error even includes so many traits. This is what the macro expands to for me:
```rs
let _adw_applicationwindow_6 =
    <adw::ApplicationWindow as relm4::util::default_widgets::DefaultWidget>::default_widget();
let _gtk_box_5 =
    <gtk::Box as relm4::util::default_widgets::DefaultWidget>::default_widget();
// ...
_adw_applicationwindow_6.set_child(Some(&_gtk_box_5));
// ...
```

**Comment by overlisted** [comment]
The first solution has been added to v0.1.0-beta.8.
