### ISSUE TITLE
Cannot use own struct name in derive macro for components

### ISSUE THREAD

**Issue by flosse** [AaronErhardt/Relm4#115]
My main app widgets struct is called `View` but if I use 
```rust
#[derive(relm4::Components)]
struct AppComponents {
    foo: AsyncRelmWorker<foo::Mdl, Mdl>,
}
```
it does not compile because the macro assumes it is always `AppWidgets`:

https://github.com/AaronErhardt/Relm4/blob/5f926dc2d0533543c965107a8d28a3163e195d07/relm4-macros/src/derive_components/mod.rs#L131

**Comment by AaronErhardt** [comment]
Thanks for the report! I'm surprised this is reported just now, but maybe `AppWidgets` is just very popular...

I've just sent a patch. Can you test if that fixes the bug for you?

**Comment by flosse** [comment]
@AaronErhardt thanks for that quick reply and fix!
It's working now :+1: 

BTW: Is there a way to use a different name as `model` in the `view!` macro?
