### ISSUE TITLE
New component macro: how do you use `Self::Widgets` inside `watch!`?

### ISSUE THREAD

**Issue by cofee-on-the-desk** [AaronErhardt/Relm4#117]
When I implement component manually, I can use `Self::Widgets` to refer to application widgets:

```rust
...
fn update_view(
        &self,
        widgets: &mut Self::Widgets, // widgets struct here
        input: &Sender<Self::Input>,
        output: &Sender<Self::Output>,
    ) {
        widgets.label.set_label(&format!("{:?}", widgets.gtk_box)); // allows us to do something like this
    }
```
    
But I don't see a way to use this struct in macro, when using `watch!` (or `pre_view` / `post_view`):

```rust
...
    set_child: gtk_box = Some(&gtk::Box) {
        append: label = &gtk::Label {
            set_label: watch!(&format!("{:?}", gtk_box)),
        },
    },
```

```rust
error[E0425]: cannot find value `gtk_box` in this scope
  --> src/main.rs:28:56
   |
28 |                     set_label: watch!(&format!("{:?}", gtk_box)),
   |                                                        ^^^^^^^ not found in this scope
```

Neither `gtk_box`, `self.gtk_box` or `widgets.gtk_box` are defined, so how do I use the struct here?

Tested the same thing in 0.4 version. Still impossible in `watch!`, but `pre_view` / `post_view` allow it.

**Comment by AaronErhardt** [comment]
I will try fixing watch!, yet pre_view and post_view should still work the same in 0.5... I will have a closer look this afternoon.

**Comment by cofee-on-the-desk** [comment]
Okay, `pre_view` and `post_view` are now working for me. I might've made a mistake somewhere, sorry.

**Comment by AaronErhardt** [comment]
Should be fixed now on both stable and new-approach.

**Comment by cofee-on-the-desk** [comment]
The above example now compiles and works correctly. Thanks for the fix.
