### ISSUE TITLE
new-approach: factories use the wrong Sender

### ISSUE THREAD

**Issue by cofee-on-the-desk** [AaronErhardt/Relm4#123]
Factories use `gtk::glib::Sender`, while components use `relm4::Sender`, making them incompatible. Also, as a side note, the `Factory::generate` method should probably take the sender by reference, so users don't have to clone it manually.

**Comment by AaronErhardt** [comment]
Yep, factories are kind of broken on new-approach still. I'm currently planning to make factories use `Component` instead of `FactoryPrototype`, which would make things simpler and eliminate yet another trait.

**Comment by AaronErhardt** [comment]
Should be fixed now.
