### ISSUE TITLE
How to use #[relm4_macros::widget] with initializer

### ISSUE THREAD

**Issue by tronta** [AaronErhardt/relm4#13]
I want to add a scale widget. How can I add this in the macro with the proper initialization
```
pub fn with_range(
    orientation: Orientation,
    min: f64,
    max: f64,
    step: f64
) -> Scale
```
At least I have not seen how I can add those parameters afterwards.
Maybe you could add in the documentation how to do that.

**Comment by AaronErhardt** [comment]
I think this is what you're looking for: https://aaronerhardt.github.io/relm4-book/book/widget_macro_reference.html#functions

**Comment by tronta** [comment]
Ah, sorry. I haven't read through all of it yet.
Maybe it makes sense to add a sentences that other cases than the default implementation will be described later.

**Comment by tronta** [comment]
Maybe can you elaborate a little how I can do this in detail? The explanation in the documentation did not help me.
Maybe a concrete example could help. That would be great.

**Comment by AaronErhardt** [comment]
If you want to use a function to initialize a widget you just need to use

```rust
property_name = gtk::Scale::with_range(gtk::Orientation::Vertical, 0.0, 100.0, 1.0)  { ... }
```

instead of

```rust
property_name = gtk::Scale { ... }
```

I think `gtk::Scale` has no proper setter and getter methods for min and max values so you need to use the constructor function.

**Comment by AaronErhardt** [comment]
Was that explanation helpful or is it still unclear?

**Comment by tronta** [comment]
Actually it was very easy, after trying it. Probably, I was just a little be confused as it is described in the back with some little text.
For me at least, it would have helped, even more, if there would be something in the running code.
The whole thing is simple enough to be added in the first example.

What about changing the creation of one of the buttons in the first example like this:
```
use gtk::prelude::{BoxExt, ButtonExt, GtkWindowExt, OrientableExt};
use relm4::{send, AppUpdate, Model, RelmApp, Sender, WidgetPlus, Widgets};

#[derive(Default)]
struct AppModel {
    counter: u8,
}

enum AppMsg {
    Increment,
    Decrement,
}

impl Model for AppModel {
    type Msg = AppMsg;
    type Widgets = AppWidgets;
    type Components = ();
}

impl AppUpdate for AppModel {
    fn update(&mut self, msg: AppMsg, _components: &(), _sender: Sender<AppMsg>) -> bool {
        match msg {
            AppMsg::Increment => {
                self.counter = self.counter.wrapping_add(1);
            }
            AppMsg::Decrement => {
                self.counter = self.counter.wrapping_sub(1);
            }
        }
        true
    }
}

#[relm4_macros::widget]
impl Widgets<AppModel, ()> for AppWidgets {
    view! {
        gtk::ApplicationWindow {
            set_title: Some("Simple app"),
            set_default_width: 300,
            set_default_height: 100,
            set_child = Some(&gtk::Box) {
                set_orientation: gtk::Orientation::Vertical,
                set_margin_all: 5,
                set_spacing: 5,

                append = &gtk::Button {
                    set_label: "Increment",
                    connect_clicked(sender) => move |_| {
                        send!(sender, AppMsg::Increment);
                    },
                },
                append = &gtk::Button::with_label("Decrement") {
                    connect_clicked(sender) => move |_| {
                        send!(sender, AppMsg::Decrement);
                    },
                },
                append = &gtk::Label {
                    set_margin_all: 5,
                    set_label: watch! { &format!("Counter: {}", model.counter) },
                }
            },
        }
    }
}

fn main() {
    let model = AppModel::default();
    let app = RelmApp::new(model);
    app.run();
}

```

**Comment by AaronErhardt** [comment]
Sounds like a good idea. I will add this to the book. Thanks a lot for your feedback!

**Comment by AaronErhardt** [comment]
I added your example to the book and added some headings to make it more clear: https://aaronerhardt.github.io/relm4-book/book/widget_macro.html
What do you think?

**Comment by tronta** [comment]
Looks good! Thanks.
