### ISSUE TITLE
new approach: `init` should not be a method on `Component`

### ISSUE THREAD

**Issue by euclio** [AaronErhardt/Relm4#140]
The current design of the `Component` trait expects users to initialize a `ComponentBuilder` by calling `init()` on their `Model`. This feels weird to me, since reading `YourModel::init()` looks like it creates an instance of `YourModel`, not `ComponentBuilder`. Also, having it be a trait method allows users to override it in their `Component` impl, which is never something they should do.

Instead, why not define a method `ComponentBuilder::new()` that constructs a new builder, with the component type specified as a type parameter? This makes it clearer that a component is being constructed, and type inference will usually allow the model type to be inferred anyways. Another benefit of moving the method is that it would free up the valuable name `init` to be used instead of `init_parts`.

**Comment by AaronErhardt** [comment]
I agree, that seems to be a more idiomatic way to handle this. Any thoughts from your side @mmstick?

**Comment by mmstick** [comment]
Yeah that's fine

**Comment by mmstick** [comment]
It may also be good if the component trait instead had a `::builder()` method which calls this. That's usually the API that people expect with creating a builder.

**Comment by AaronErhardt** [comment]
Fixed by #142

**Comment by euclio** [comment]
I've been thinking about the builder more, and I think we could go a bit further: why not provide the builder methods on `Controller` itself? That makes the API a lot more discoverable. You want to create a Controller eventually, so you can start there.

IMO it would be great if we could make the invocation look like this:

```rust
val component_params = ...;

let controller: Controller<MyComponent> = Controller::builder(component_params)
  .transient_for(...)
  .connect_receiver(...);
```

This gives us fewer builder "steps" to expose. Instead of `ComponentImpl` -> `ComponentBuilder` -> `Connector` -> `Controller`, you have `ControllerBuilder`, which lets you call `transient_for`, `update_root`, etc. and then `detach`, `forward`, etc. all start the component internally and consume the builder, giving you a component.

**Comment by AaronErhardt** [comment]
I like your idea. Yet, the reason for allowing to `launch` later on is to help with ordering.

For example, you want to attach the root of your component to your view but also pass a widget from the view (for example a `TabView` for a `TabBar` of the component). With your approach you now have a conflict: You need the view to attach the component but you also need the view to initialize the component. 

Maybe we can make it possible to skip the builder part if you have the init params ready from the start.

**Comment by euclio** [comment]
I see. Sounds like a good first step would be to add an example to the repo demonstrating `TabView`/`TabBar` usage so that we can be sure that is supported, and then we can experiment with simplifying the builder.
