### ISSUE TITLE
Launching component commands directly

### ISSUE THREAD

**Issue by mmstick** [AaronErhardt/Relm4#149]
I'm wondering if it'd be better if there wasn't a command type optionally returned on updates, but instead a mechanism for sending commands as futures.

```rs
sender.command(|out, shutdown| async move { });
```

Which would be combined with https://github.com/AaronErhardt/Relm4/pull/147 and https://github.com/AaronErhardt/Relm4/issues/148

**Comment by AaronErhardt** [comment]
I don't see any disadvantage. In fact, this should make things even more flexible because you can then send multiple commands.
