### ISSUE TITLE
Pub (crate) option for #[relm4_macros::widget]

### ISSUE THREAD

**Issue by a-kenji** [AaronErhardt/relm4#24]
Thanks for the library!
It's fun to explore it.
Is there a way to set the pub (crate) option through the #[relm4_macros::widget(pub)] macro?

**Comment by AaronErhardt** [comment]
Not yet, but it should be easy to this. I'll try to write a path for this.

**Comment by a-kenji** [comment]
Awesome, thank you!

**Comment by AaronErhardt** [comment]
I've fixed it now. The macro should now accept all kinds of visibilities.

For now, you can use the version from git if you want. The next release will be in a few days, I think.

**Comment by a-kenji** [comment]
Thank you for the quick work! No need to pressure for a release,
I am fine with the gh version for now.
