### ISSUE TITLE
factory key should be unsized

### ISSUE THREAD

**Issue by mskorkowski** [AaronErhardt/relm4#53]
In data store there is an id type which is being used to identify the records in the store. It's generic in terms of values which are used. By default I'm using uuid's since they are easily unique. But it's widespread to use `i32` or something bigger as ids. So I need to provide ability to change what kind of values are stored inside.

This on the other hand interferes with `Factory::Key` which is `Sized` by default.

PR: #52

**Comment by AaronErhardt** [comment]
Makes sense. PR is merged.
