### ISSUE TITLE
Support for dynamically created components ?

### ISSUE THREAD

**Issue by HuangBoHong** [AaronErhardt/relm4#56]
As far as I am aware, factory collections exist in relm4 to create dynamic view and manage them in various layouts, but the dynamically created widgets can be complicated, so I want to create them into a component and build them with the `view!` macro. I wonder if it's possible to use factory collection in conjunction with component ?

**Comment by AaronErhardt** [comment]
There's a new concept called [MicroComponents](https://aaronerhardt.github.io/docs/relm4/relm4/struct.MicroComponent.html) in the latest beta releases that could be what you're looking for. They can be created dynamically and in general have less restrictions than regular components.

Yet, the widget macro hasn't been updated to support them, but hopefully I will be able to add this before the next stable release.

[Micro components example](https://github.com/AaronErhardt/relm4/blob/main/relm4-examples/examples/micro_components.rs)

**Comment by HuangBoHong** [comment]
> There's a new concept called [MicroComponents](https://aaronerhardt.github.io/docs/relm4/relm4/struct.MicroComponent.html) in the latest beta releases that could be what you're looking for. They can be created dynamically and in general have less restrictions than regular components.
> 
> Yet, the widget macro hasn't been updated to support them, but hopefully I will be able to add this before the next stable release.
> 
> [Micro components example](https://github.com/AaronErhardt/relm4/blob/main/relm4-examples/examples/micro_components.rs)

That is exactly what I want, since I found it possible to create `MicroComponent` dynamically and integrate it into factory collection. Can't wait for the next stable release :)

**Comment by paulolieuthier** [comment]
@BohongHuang could you share how you combined factories with components?

**Comment by BohongHuang** [comment]
> @BohongHuang could you share how you combined factories with components?

Well. First you will need to create a type wrapper such as `MyComponent` for the foreign type `MicroComponent` from `relm4`:

``` rust
pub struct MyComponent<T: MicroModel> {
    pub component: MicroComponent<T>,
}

impl <Model> MyComponent<Model>
where
    Model::Widgets: MicroWidgets<Model> + 'static,
    Model::Msg: 'static,
    Model::Data: 'static,
    Model: MicroModel + 'static, {
    pub fn new(model: Model, data: Model::Data) -> MyComponent<Model> {
        MyComponent { component: MicroComponent::new(model, data) }
    }
}
```

Then implement `FactoryPrototype` for the type wrapper. It is worth mentioning that `MicroComponent::update_view` should be called when you implement the method `view`: 

``` rust
impl FactoryPrototype for MyComponent<MyModel> {
    type Factory = FactoryVec<Self>;
    type Widgets = ToastOverlay;
    type Root = ToastOverlay;
    type View = Grid;
    type Msg = AppMsg;

    fn init_view(
        &self,
        _index: &usize,
        _sender: Sender<AppMsg>,
    ) -> ToastOverlay {
        self.component.root_widget().clone()
    }

    fn position(
        &self,
        index: &usize,
    ) -> GridPosition {
        let index = *index as i32;
        let row = index / 3;
        let column = index % 3;
        GridPosition {
            column,
            row,
            width: 1,
            height: 1,
        }
    }

    fn view(
        &self,
        _index: &usize,
        _widgets: &ToastOverlay,
    ) {
        self.component.update_view().unwrap();
    }

    fn root_widget(widgets: &ToastOverlay) -> &ToastOverlay {
        widgets
    }
}
```

Now you can implement `MicroModel` and `MicroWidgets` for your model: 

``` rust
impl MicroModel for SlaveModel { ... }

#[micro_widget(pub)]
impl MicroWidgets<SlaveModel> for SlaveWidgets { ... }
```

And add the model wrapped by `MyComponent` to a `FactoryVec`: 

``` rust
models: FactoryVec<MyComponent<MyModel>>
```

Finally, apply macro `factory!` in your factory widget: 

``` rust
Grid {
    factory!(model.models),
}
```

**Comment by paulolieuthier** [comment]
Thanks!
