### ISSUE TITLE
Do not use gtk::Application's command-line argument handling by default

### ISSUE THREAD

**Issue by euclio** [AaronErhardt/relm4#59]
relm4 invokes `gtk::Application::run` which will attempt to automatically handle command-line arguments from the environment. This leads to the surprising behavior that if you supply *any* arguments to a relm4 application, you'll get a `Glib-GIO-CRITICAL` warning "This application can not open files." and the application will immediately exit.

I'd like to propose that `RelmApp::run` instead invokes `gtk::Application::run_with_args(&[])`, and provide a `RelmApp::run_with_args()` for users that want to opt-in to `gtk::Application`'s argument handling.

If this sounds reasonable, I'm happy to open a PR.

**Comment by AaronErhardt** [comment]
Sounds good, I'd be happy to merge this :)
