### ISSUE TITLE
Simplest way to display a list of strings

### ISSUE THREAD

**Issue by ArekPiekarz** [AaronErhardt/relm4#63]
I wanted to create a Relm4 app with a static list view, displaying some text in each line. I stumbled upon this example - https://github.com/AaronErhardt/relm4/blob/main/relm4-examples/examples/list.rs. I was surprised how much boilerplate has to be implemented just to display a number:

We need to create GIntegerObject, implement ObjectSubclass and ObjectImpl for it, subclass it in IntegerObject, implement its creation with glib::Object, then for gtk::ListView it is required to provide data with gio::ListStore and to setup gtk::SignalListItemFactory for mapping between a few property expressions and a widget.

I was wondering it this is really a bare minimum or is there a simpler way to display a list of strings? I know it was much easier when I was using gtk::TreeView and gtk::ListStore from GTK3 Rust bindings - there was no need to create new classes or implement any traits, while mapping to widgets was done simply by choosing a cell renderer. I am also aware this question may be aimed more towards GTK than Relm, but the example exists in this repository.

**Comment by AaronErhardt** [comment]
The list view example is mostly an port of the list view example in the gtk-rs book.
Relm4 has factories for widget lists that are described in the Relm4 book. They have some limitations but require a lot less code and are much more idiomatic.

**Comment by AaronErhardt** [comment]
The list view example is mostly an port of the list view example in the gtk-rs book.
Relm4 has factories for widget lists that are described in the Relm4 book. They have some limitations but require a lot less code and are much more idiomatic.

**Comment by AaronErhardt** [comment]
And there's also the ongoing effort to bring a data store to Relm4: https://github.com/AaronErhardt/relm4/issues/46
It looks pretty promising and I hope this will be stable soon.

**Comment by ArekPiekarz** [comment]
Thanks for the tips. I don't know how to use the factory as a provider for items inside gtk::ListView and the Relm's data store is not yet available, so I went back to gtk::TreeView with gtk::ListStore.

**Comment by mskorkowski** [comment]
@ArekPiekarz If you can spare a few min and check if examples in `https://github.com/mskorkowski/relm4-store` at branch `housekeeping/after_soring` meet your needs `todo_2` or `todo_2_single_scroll` might by interesting for you. 

I think API is pretty stable now and I think we are at the stage we can start releasing it. My plans before marking it good to go was to describe all todo examples in the book but that can be done independently.
