### ISSUE TITLE
Transient dialogs shift on subsequent view calls when using `libadwaita`

### ISSUE THREAD

**Issue by Paveloom** [AaronErhardt/relm4#66]
The following can be observed in the [`calc-trainer`](https://github.com/AaronErhardt/relm4/blob/main/relm4-examples/libadwaita/examples/calc-trainer.rs) example.

Pressing "Start" starts a timer, after which a transient `DialogMsg` widget appears.

First call:
![1](https://user-images.githubusercontent.com/49961859/147887238-051afba8-dad8-417c-b4b1-46dda173313a.png)

Second and subsequent calls:
![2](https://user-images.githubusercontent.com/49961859/147887241-80f42dbb-6840-400a-892a-9872e79c6cdb.png)

Same happens with the `AboutDialog` and `ShortcutsWindow` widgets in [my project](https://github.com/paveloom-a/Tidings).

I'm not sure whether it's a Relm4 issue or not, but I couldn't find the same behavior in [Rnote](https://github.com/flxzt/rnote) (gtk4-rs + libadwaita-rs), for example.

**Comment by AaronErhardt** [comment]
The example seems to do this correctly, it uses `set_transient_for`: https://github.com/AaronErhardt/relm4/blob/7ba13fa4a0f0eb25ca5a082292b16920ec7b55c9/relm4-examples/libadwaita/examples/calc-trainer.rs#L68

Also I can't reproduce this bug on my machine. Maybe this was a bug in libadwaita that's already fixed? I can't tell, I can only say that I still haven't updated libadwaita to 1.0 because of GTK 4.5 which isn't yet available on Ubuntu.

Rnote might not be affected because of flatpak...

@tronta can you reproduce the bug?

**Comment by Paveloom** [comment]
> Rnote might not be affected because of flatpak...

I have a Flatpak [workflow](https://github.com/paveloom-a/Tidings/blob/main/run.bash) set up in my project, you can try the script, if you'd like. It should reproduce the issue.

Also, check out [Meson dependencies](https://github.com/paveloom-a/Tidings/blob/main/manifests/dev.yml) and [`Cargo.toml`](https://github.com/paveloom-a/Tidings/blob/main/Cargo.toml).

**Comment by Paveloom** [comment]
Huh, apparently only occurs on Wayland (when `--socket=wayland` is enabled).

**Comment by AaronErhardt** [comment]
Does it also happen for Rnote with Wayland? In any case, this doesn't look like Relm4 is the problem here...

**Comment by Paveloom** [comment]
No, Rnote behaves as expected.

Okay, I can reproduce the same issue with the [`components`](https://github.com/AaronErhardt/relm4/blob/main/relm4-examples/examples/components.rs) example, both with Relm4 `v0.4.0-beta.3` and `v0.2.1`:

First call:
![1](https://user-images.githubusercontent.com/49961859/147912308-2d23943d-9ac4-4a98-92b1-16bea72bbafb.png)

Second and subsequent calls:
![2](https://user-images.githubusercontent.com/49961859/147912313-da793a1f-3a18-46be-846b-8409b5a06c24.png)

It slightly moved to the right.

So, it's not `libadwaita`'s fault. I started with `gtk4-rs`, so my first [commit](https://github.com/paveloom-a/Tidings/tree/f6a87603fa56c51a00d03afd66ceef481591a715) is the same "Hello world!" application written in pure `gtk4-rs`. It's based on [`gtk-rust-template`](https://gitlab.gnome.org/bilelmoussaoui/gtk-rust-template). I can reproduce the same issue there, too.

Hence, it's either `gtk-rs`'s or GTK4's issue. Closing.

**Comment by Paveloom** [comment]
See also: [GNOME/gtk#4636](https://gitlab.gnome.org/GNOME/gtk/-/issues/4636).
