### ISSUE TITLE
Expose `menu!` macro beyond `view!`

### ISSUE THREAD

**Issue by euclio** [AaronErhardt/Relm4#70]
The menu macro is only usable from inside `view!`, but it could be useful even in manually constructed views. Is it possible to expose its functionality outside of `view!`?

**Comment by AaronErhardt** [comment]
Should be possible and even quote easy to implement.

**Comment by AaronErhardt** [comment]
What do you think about this: https://github.com/AaronErhardt/Relm4/blob/main/relm4-examples/examples/menu.rs#L91

(relevant commit:  db175e87f469c23f173e1a376557a989260df491)

**Comment by euclio** [comment]
Looks great!
