### ISSUE TITLE
How can I get the value of the Entry?

### ISSUE THREAD

**Issue by QuintinTao** [AaronErhardt/Relm4#72]
I want to get the user_name and passwords' values when I click the btn submit.

```rust
                 append = &gtk::Entry {
                        //set_buffer: &model.entry,
                        set_tooltip_text: Some("username"),
                        connect_activate(sender) => move |_| {
                            //send!(sender, AppMsg::get_user_name);
                        },
                    },
                 },
```

I want to get the Entry value when I click the sumit btn.

```rust
             append = &gtk::Box {
                    set_orientation: gtk::Orientation::Horizontal,
                    set_spacing: 10,
                    append = &gtk::Button {
                        set_label: "login",
                        connect_clicked(sender) => move |_| {
                           // **how can I get the Entry value here?**
                            send!(sender, AppMsg::Login((model.user_name, model.password)));
                        },
                    },
                    append = &gtk::Button {
                        set_label: "reg",
                        connect_clicked(sender) => move |_| {
                            send!(sender, AppMsg::Reg);
                        },
                    },
                },
```

**Comment by QuintinTao** [comment]
it does help me！thanks
By the way how can I learn relm？ I need some doc to learn API .

> There are two options:
> 
> 1. You store the value of the entry in your model. The easiest way to do this is to create an [`EntryBuffer`](https://gtk-rs.org/gtk4-rs/git/docs/gtk4/struct.EntryBuffer.html) and store it inside the model. Then you use [`set_buffer`](https://gtk-rs.org/gtk4-rs/git/docs/gtk4/prelude/trait.EntryExt.html#tymethod.set_buffer) to set the buffer of the entry in the `view!` macro. Whenever you want to get the value of the entry you can the just call [`self.buffer_name.text()`](https://gtk-rs.org/gtk4-rs/git/docs/gtk4/prelude/trait.EntryBufferExtManual.html#tymethod.text) in the `update` method.
> 2. You name your entries and move them into the button closure:
> 
> ```rust
> connect_clicked(sender, entry1_name, entry2_name) => move |_| {
>    let user_name = entry1_name.buffer().text();
>    let password = entry2_name.buffer().text();
>    send!(sender, AppMsg::Login((user_name, password)));
> },
> ```
> 
> I hope this helps you :)

It does help me. Thanks .by the way where can I learn relm.I mean the api.

**Comment by AaronErhardt** [comment]
You can learn Relm4 with the book, the examples or the documentation. You can find all those links in the Readme.
Also, this article might help you: https://aaronerhardt.github.io/blog/posts/gui_speedrun/
