### ISSUE TITLE
I use relm 4 0.2.1 ，menu demo doesn't exist.

### ISSUE THREAD

**Issue by QuintinTao** [AaronErhardt/Relm4#74]
example/menu.rs

I find this demo in the 0.4.0-beta.3 。

I copy it into my project， but this method doesn't exist.

menu! {

![image](https://user-images.githubusercontent.com/72123724/148917908-40aee543-ae4d-4de2-b1d8-51a1978932f6.png)

How can I pass data to the main_menu

 add_child: intro_label = &gtk::Box {
                        append = &gtk::MenuButton {
                            set_menu_model: Some(&**main_menu**),
                        },
                    },

**Comment by QuintinTao** [comment]
please share me a demo about how to use menu button in 0.2.1

**Comment by AaronErhardt** [comment]
Yes, menu! is a macro introduced in the 0.4 beta. It will be released soon as stable. If you want to use it you can already upgrade to 0.4.0-beta.3

You can always create a menu manually with this type: https://gtk-rs.org/gtk-rs-core/git/docs/gio/struct.Menu.html
Yet, that's rather tedious.

You can also use .ui files like described here: https://gtk-rs.org/gtk4-rs/git/book/actions.html
But this also requires some additional work to get it going.

**Comment by QuintinTao** [comment]
> Yes, menu! is a macro introduced in the 0.4 beta. It will be released soon as stable. If you want to use it you can already upgrade to 0.4.0-beta.3
> 
> You can always create a menu manually with this type: https://gtk-rs.org/gtk-rs-core/git/docs/gio/struct.Menu.html Yet, that's rather tedious.
> 
> You can also use .ui files like described here: https://gtk-rs.org/gtk4-rs/git/book/actions.html But this also requires some additional work to get it going.

thanks！
