### ISSUE TITLE
Names of the new component parts

### ISSUE THREAD

**Issue by AaronErhardt** [AaronErhardt/Relm4#89]
# Current state

## Component initialization

`Bridge (+Payload, Fuselage) --launch--> Fairing --detach--> Controller`

> The problem I see with these names is that they are hardly known to people who learned English as a second language-

### Bridge
- Gives you access to the root widget
- Can be converted into `Fairing` with a given `Payload`
- During the conversion, it spawns the runtime that handles incoming messages (and runs commands)

### Fairing
- Either spawn a new runtime to forward messages from the component with a given sender
- Or connect a function that receives messages from the component and can forward the messages
- Or do nothing
- Converts itself into an controller

### Controller
- Gives you access to the root widget
- Allows you to send messages to the component
- *This is what you want to keep in your model*

# Alternative names

+ Alternative rocket analogy: `Base Frame (+Payload, Parts) --assemble--> Rocket/Aircraft --launch--> Controller`
+ Classical programming terms: `Builder (+InitParams, ComponentParts) --build--> Connector --connect/get_handle--> Handle`

**Comment by mskorkowski** [comment]
I would choose the "classical programming terms" except the case I would like to make it distinct from other libraries for some reason.

In relm4-store there is `Record` instead of `Model` since model is used by the relm4.

**Comment by euclio** [comment]
I dislike the rocket/aircraft terminology as well. Even as a native English speaker I have never heard the term "fairing" before.

The "classical" terms sound pretty good to me. I'd probably go with something like

- `Bridge::init` -> `Builder::new_component`, or `Builder::init_component`. These names make it clearer that you're creating a new component from a model.
- `Bridge::launch` -> `Builder::start`
- `Fuselage` -> `(Model, Widget)` (I don't see a need to name this type, but maybe we should for future compat reasons?)
- `Fairing` -> `Handle` (not super happy about this one, feels like its methods should be on the builder, but not callable until it's been started. Maybe this is representable as a type-level state machine?).
- `connect_receiver` -> `update`, `on_update`, or `on_message`
