### ISSUE TITLE
Relm4 logo is cut off on its right

### ISSUE THREAD

**Issue by MicroJoe** [AaronErhardt/relm4#9]
Hello,

Thanks for this crate, I am interested in using it in the near future for GTK app development.

One of the first things that I noticed in the README is that the SVG logo is cut off on the right side. This may be because the font rendering on my system differs from yours. One solution would be to convert the text to paths (if not done yet) in order to be sure that the rendering is system-independent.

Here is a screenshot of the SVG file from Github, with the cutoff on its right side:

![Capture d’écran de 2021-08-13 11-47-05](https://user-images.githubusercontent.com/989521/129339068-98071c80-6bba-44a3-9aa3-9b79cb14ba00.png)

Thanks in advance for your time.

**Comment by PolyMeilex** [comment]
For me its different font and different size then your's, so it for sure is not a path (look good here tho)

**Comment by MicroJoe** [comment]
Thanks for the feedback, so I guess you have the correct font on your system (`Fira Sans` according to its source code), but not me and probably nor other users. Can you export the text to a SVG path on your system with the correct font installed, and update the logo?

**Comment by AaronErhardt** [comment]
@MicroJoe thanks for pointing this out! I just converted the text to a path in Inkscape. Can you tell me if the latest commit fixed this issue for you?

**Comment by MicroJoe** [comment]
Hi Aaron, thanks! The latest commit fixed the issue on my side perfectly, see the below screenshot:

![Screenshot where the logo appears without borders cut](https://user-images.githubusercontent.com/989521/129439088-d87a91d1-abcc-4bea-9fb4-05159ebc6331.png)

Looking forward to use (and contribute to) Relm4!
