### ISSUE TITLE
Creating micro-components "early" causes a segfault

### ISSUE THREAD

**Issue by roblabla** [AaronErhardt/Relm4#92]
Hello,

The following code causes a segfault:

```rust
use relm4::factory::{FactoryVec, FactoryPrototype};
use relm4::{gtk, adw, send, AppUpdate, Model, RelmApp, Widgets, Sender, MicroComponent, MicroWidgets, MicroModel};
use relm4::gtk::prelude::*;
use relm4::adw::prelude::*;
use relm4::util::widget_plus::WidgetPlus;


#[derive(Debug)]
struct ActOverview;

impl MicroModel for ActOverview {
    type Msg = ();
    type Widgets = ActOverviewWidgets;
    type Data = ();

    fn update(&mut self, _msg: (), _data: &(), _sender: Sender<Self::Msg>) {
    }
}

#[relm4::micro_widget]
#[derive(Debug)]
impl MicroWidgets<ActOverview> for ActOverviewWidgets {
    view! {
        gtk::Box {
            set_orientation: gtk::Orientation::Vertical,
        }
    }
}


fn main() {
    MicroComponent::new(ActOverview, ());
}
```

I believe this happens because `MicroComponent::new` calls some GTK methods before `gtk::init` got called. This reproducer is obviously quite synthetic (you wouldn't normally do this X)). What I wanted to do was prepopulate a model with a `Vec<MicroComponent<ActOverview>>` containing some pre-created micro-components (the vec would then get modified during the lifetime of the program). What's the recommended way of populating a model with some microcomponent on startup?

**Comment by AaronErhardt** [comment]
You can always call `gtk::init()` yourself. 

Yet, I think calling `gtk::init()` is rather cheap and it could be added to `MicroComponetn::new` so that this issue can never happen.

**Comment by AaronErhardt** [comment]
I've added a patch the calls `gtk::init()` in `MicroComponent::new`. I will publish this as new point release soon.

**Comment by AaronErhardt** [comment]
Should be fixed now with the latest point release.
